baseURL = "https://fcalabria.github.io/hard-drive/"
languageCode = "en-us"
title = "Hard drive"
theme = "hugo-theme-learn"
publishDir = "../"

[params]
editURL = "https://github.com/FCalabria/hard-drive/tree/master/src/content/"
author = "FCalabria"

[outputs]
home = [ "HTML", "RSS", "JSON"]